[package]
name = "budgers"
version = "0.1.0"
authors = ["Eitan Mosenkis <eitan@mosenkis.net>"]
edition = "2018"

[dependencies]
strum = "0.19.2"
strum_macros = "0.19.2"
shrinkwraprs = "0.3.0"

[dependencies.bevy]
git = "https://github.com/emosenkis/bevy"
rev = "3483204ddfedf3a15ec796988c30ebdcafd2fcfd"
default_features = false
features = ["bevy_winit", "bevy_wgpu", "render", "png", "x11"]
